### ISSUE TITLE
Tests with minimum RuboCop version

### ISSUE THREAD

**Issue by marcandre** [rubocop/rubocop-performance#112]
The minimum version of RuboCop needs to be bumped ([to at least 0.82](https://github.com/rubocop-hq/rubocop-performance/issues/111)), and more importantly CI needs to test with whatever the minimum version of RuboCop is, as well as with `master`.

**Comment by koic** [comment]
The next released version as bugfix version 1.6.1, so supported RuboCop core version remains unchanged (#111 will be fixed with the old API).
RuboCop Performance 1.7 will drop some older RuboCop support versions (and using new API).

Anyway, supported RuboCop core versions should be included in the CI matrix. I will take this later. Thank you for investigating and suggestion!

**Comment by pirj** [comment]
We had [this idea in `rubocop-rspec`](https://github.com/rubocop-hq/rubocop-rspec/pull/815#issuecomment-541202240) and dropped it for one reason - with RuboCop 1.0 on the horizon and its conservative policy of breaking changes, it should not be a problem, we don't expect breakages for any of the versions satisfying `rubocop ~> 1.0`.

**Comment by koic** [comment]
https://github.com/rubocop/rubocop-performance/pull/235 and https://github.com/rubocop/rubocop-performance/commit/3a7024e close this issue because it implements versioning (`'>= 1.y', '< 2.0'`) similar to @pirj's opinion. Thank you.
